### PR TITLE
Closure Subset C

### LINKED ISSUE #57: Double SIGINT on openmctStaticServer process still triggering uncaught SIGINT event
The issue fixed in in #44 (refer to https://github.com/ami-iit/yarp-openmct/issues/44#issuecomment-946823979_) is still present.

> - When interrupting the app sending `<CTRL+C>` from the terminal stdin, a group SIGINT event is generated and sent to all running processes in the group (`node icubTelemVizServer.js` and `node server.js`).
> - As a consequence two SIGINT events are captured in the child process `node server.js`: the one received directly through the group SIGINT, and the one forwarded from the parent process through a `kill -s INT` command.
> - The double event processing causes a premature, potentially problematic, closure of the child process and underlying tasks, and this is due to the fact that the second event is processed by the default SIGINT handler.
> 
> ### Solution
> - We stop listening to the SIGINT events while we wait for the server closure to be completed. Such wait should be limited by a timeout for avoidning a lock in case of an unexpected issue delays the server closure indefinitely.
> 

It was happening occasionally, and commenting the removal of the timeout and the idle listener implemented in 75b6fe8471062999795663fb770448293d429eb3 would avoid the issue, but this has to be properly fixed.

### PR DESCRIPTION
**Pull request by nunoguedelha**
Implements #54 .
Fixes #57 .

### CODE REVIEW

File: iCubTelemVizServer/terminationHandler.js [hunk 1]
```diff
@@ -45,23 +53,45 @@ TerminationHandler.prototype.runSubsetA = function (signal) {
...
      * B.1 - Stop listening to client requests ("subscribe"/"unsubscribe" events) on the existing connections.
+     * B.2 - Close the YARP ports connections associated to the telemetry entries in `portInConfig` and instantiated by the main Node.js process.
+     * B.3 - Stop reading the respective YARP ports (similar to turning off the port listeners).
+     * B.4 - Stop sending "real-time telemetry data" messages (notifications) to subscribers.
      */
-     this.telemServerTracker.pauseAll();
+     console.log(resValue);              // consume resolve value from previous promise (synch operation)
+     this.telemServerTracker.pauseAll(); // Stop listening to client requests (synch operation)
+     console.log('iCub Telemetry Server closing: no further "subscribe"/"unsubscribe" requests accepted.');
+     this.unlistenToYarpPorts.forEach((disconnect) => { disconnect(); }); // Disconnect all telemetry entries (asynch operation)
```
Comment (S-Dafarra) [inline iCubTelemVizServer/terminationHandler.js:77]: Just FYI, when calling the ``close`` method on a port, the disconnections are handled automatically.

**Review by S-Dafarra — APPROVED** [review]

File: iCubTelemVizServer/terminationHandler.js (hunk 1 above)
Comment (nunoguedelha) [reply iCubTelemVizServer/terminationHandler.js:77]: Good point. I had the following reasons:
- Initially I was leaving the ports closure to the `Yarp.js` module which does it automatically when the process exits (https://github.com/robotology/yarp.js/blob/ceddda861b1b29478d3bc389d83765fed7297196/yarp.js#L201-L205).
- Nevertheless, I wanted the state of the Yarp ports to be consistent with the local disconnection on the Node.js side, and the calls to the Yarp port listeners to stop.

At this point, there is something left in the Node Event Loop, preventing the process to exit on its own (without explicitly calling `process.exit()`, which is not recommended), so I'm trying to see what happens if I close the ports manually (not committed here). I doubt but if that helps, I'll replace the ports disconnection by the direct closure.

Comment (S-Dafarra) [reply iCubTelemVizServer/terminationHandler.js:77]: Ok clear, I was just curious.
